# -*- coding: utf-8 -*-
"""Introdução a machine learning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CetS8EtK6tBauRoPDRsmwaUoFNAuI-kb
"""

import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
from prophet import Prophet #trabalhar com series temporáis

# Baixar dados dos últimos quatro anos para uma ação específica
dados = yf.download("JNJ", start="2020-01-01", end="2023-12-31", progress=False) #progress é so visual para mostrar o download
dados = dados.reset_index()

# Vamos dividir os dados em treino (até o final do primeiro semestre de 2023) e teste (segundo semestre de 2023)
dados_treino = dados[dados['Date'] < '2023-07-31']
dados_teste = dados[dados['Date'] >= '2023-07-31']

# Preparando os dados para o FBProphet que é igual a cortar colunas no excel
dados_prophet_treino = dados_treino[['Date', 'Close']].rename(columns={'Date': 'ds', 'Close': 'y'})

# Criar e treinar o modelo com sazionalidades que iremos analisar
modelo = Prophet(weekly_seasonality=True,
        yearly_seasonality=True,
        daily_seasonality=False)

modelo.add_country_holidays(country_name='US') #especificando que devemos usar o feriados do USA

modelo.fit(dados_prophet_treino) #fit é seu ajuste, aprenda sobre os dados

# Criar datas futuras para previsão até o final de 2023, o modelo em si vai fazer esta atividade sozinho dado que passamos dados historicos para ele
futuro = modelo.make_future_dataframe(periods=150)
previsao = modelo.predict(futuro)

# Plotar os dados de treino, teste e previsões em visão grafica
plt.figure(figsize=(14, 8))
plt.plot(dados_treino['Date'], dados_treino['Close'], label='Dados de Treino', color='blue')
plt.plot(dados_teste['Date'], dados_teste['Close'], label='Dados Reais (Teste)', color='green')
plt.plot(previsao['ds'], previsao['yhat'], label='Previsão', color='orange', linestyle='--')

plt.axvline(dados_treino['Date'].max(), color='red', linestyle='--', label='Início da Previsão')
plt.xlabel('Data')
plt.ylabel('Preço de Fechamento')
plt.title('Previsão de Preço de Fechamento vs Dados Reais')
plt.legend()
plt.show()